### ISSUE TITLE
No support for ARM (M1)

### ISSUE THREAD

**Issue by justPaulo** [microsoft/homebrew-azdata-cli-release#23]
Error: azdata-cli: /opt/homebrew/Library/Taps/microsoft/homebrew-azdata-cli-release/Formula/azdata-cli.rb:16: syntax error, unexpected tSTRING_BEG, expecting end

Steps to reproduce: brew instal azdata-cli

OS: 11.3 (20E232)

**Comment by flexyneat** [comment]
I've got the same issue. Running Big Sur 11.3.1 on an M1 MBA

**Comment by justPaulo** [comment]
I can't understand why having Microsoft made the Azure stack (az cli, powershell, etc.) available on the macOS ARM64 doesn't do the same for azdata. Makes no sense.

**Comment by flexyneat** [comment]
Still having this issue.  I think it worked well on the previous version. This is what I get:


Error updating Azure Data CLI: Unexpected exit code from command: Error: azdata-cli: /opt/homebrew/Library/Taps/microsoft/homebrew-azdata-cli-release/Formula/azdata-cli.rb:14: syntax error, unexpected <<
<<<<<<< Updated upstream
^~
/opt/homebrew/Library/Taps/microsoft/homebrew-azdata-cli-release/Formula/azdata-cli.rb:17: syntax error, unexpected tSTRING_BEG, expecting end
    sha256 :catalina "a9de785eb27227f494a1b1509b6ac...
                     ^
/opt/homebrew/Library/Taps/microsoft/homebrew-azdata-cli-release/Formula/azdata-cli.rb:18: syntax error, unexpected tSTRING_BEG, expecting end
    sha256 :mojave "c7d93255d0775b76489a225ee7a43...
                   ^
/opt/homebrew/Library/Taps/microsoft/homebrew-azdata-cli-release/Formula/azdata-cli.rb:19: syntax error, unexpected ===, expecting end
=======
^~~
/opt/homebrew/Library/Taps/microsoft/homebrew-azdata-cli-release/Formula/azdata-cli.rb:23: syntax error, unexpected >>, expecting end
>>>>>>> Stashed changes
^~
/opt/homebrew/Library/Taps/microsoft/homebrew-azdata-cli-release/Formula/azdata-cli.rb:681: syntax error, unexpected end, expecting end-of-input (1)

**Comment by justPaulo** [comment]
@flexyneat between the previous version and your last try didn't you switch from an Intel-based Mac to an Apple Silicon M1 Mac?

**Comment by flexyneat** [comment]
Nah, Ive got only the M1 mba.

**Comment by justPaulo** [comment]
Ok, but the /opt/homebrew denotes that you also switch from the previous brew x64 to the already available brew for Apple Silicon. No logical explanation for azdata not being supported on M1, since many other MS products already do :-(

**Comment by flexyneat** [comment]
I find that I'm not able to update azdata-cli 20.3.5.

Still throws the above errors

**Comment by justPaulo** [comment]
Great news, azdata-cli installation is now working aOK for a week or so.
The previous environment I had before on Intel/AMD x64 hardware is now running fine on Apple Silicon:

$ azdata --version
20.3.5
Build (20210609.2)
SQL Server 2019 (15.0.4138)
Legal docs and information: https://aka.ms/eula-azdata-en
Python (Darwin) 3.8.10 (default, May  3 2021, 18:58:19) 
[Clang 12.0.5 (clang-1205.0.22.9)]
Python location '/opt/homebrew/Cellar/azdata-cli/20.3.5/libexec/bin/python'

Have fun

**Comment by justPaulo** [comment]
azdata-cli running on arm 64 arch as expected.
