### ISSUE TITLE
dyld: Library not loaded: @executable_path/../.Python

### ISSUE THREAD

**Issue by shiqiuKit** [microsoft/homebrew-azdata-cli-release#8]
I just brew installed v20, and got this error: 

dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/azdata-cli/20.0.0/libexec/bin/python
  Reason: image not found
/usr/local/bin/azdata: line 2:  3359 Abort trap: 6           /usr/local/Cellar/azdata-cli/20.0.0/libexec/bin/python -m azdata.cli "$@"

Need Help!

**Comment by swells** [comment]
A recent macOS patch broke this and identified on our nightly builds the other day. I will push a fix shortly and circle back.

**Comment by swells** [comment]
#9 - Resolved
When time permits could you please try uninstalling and reinstalling.

**Comment by shiqiuKit** [comment]
Thank you so much! 
I have confirmed it's fixed.
